### ISSUE TITLE
discardUncaughtJsExceptions: true not working with new runtime

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/ios#126]
Hello together,
I just came over an issue were a plugin throws an exception which lets my app crash. With the JSC runtime I can set 
discardUncaughtJsExceptions: true  
in nativescript.config.ts

and than I only get an error message as follows on the console:
NativeScript discarding uncaught JS exception!

instead of the app crashing. Seems like the new runtime does not implement this behavior. It simply always crashes.
Would be great if you could implement this option for the new runtime as well

**Comment by cjohn001** [comment]
is working with 8.5.1
